### PR TITLE
allow for module to be used with es5 applications

### PR DESCRIPTION
**Pull request by mathianasj**
In order to work with uglify, we needed to have an ES5 version published to npm

### CODE REVIEW

**Comment by odynvolk** [comment]
Hi there!

Thanks for the PR! Wouldn't it be nicer though if we used Babel from Gulp instead of ShellJS?

**Comment by mathianasj** [comment]
I will try to get it converted over tonight, thanks

**Comment by mathianasj** [comment]
I was able to replace shelljs with the gulp

**Comment by mathianasj** [comment]
Any chance you can review, and merge these changes?

**Comment by odynvolk** [comment]
Hi again!

It seems like you forgot gulp-babel in package.json. Please add it and make sure it works with a "clean" node_modules.

**Comment by odynvolk** [comment]
I'll merge it and add it myself.

**Pull request merged**
